export interface CakeItem {
  id: string;
  name: string;
  price: number;
  imageUrl: string;
  isAvailable: boolean;
  category?: string;
}

export const SAMPLE_20_CAKES: CakeItem[] = [
  {
    id: "trad-1",
    name: "Barongko Khas Bugis",
    price: 3500,
    imageUrl: "/uploads/cakes/barongko-khas-bugis.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-2",
    name: "Kue Cantik Manis Mutiara",
    price: 2500,
    imageUrl: "/uploads/cakes/kue-cantik-manis-mutiara.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-3",
    name: "Kue Klepon Gula Merah Lumer",
    price: 3000,
    imageUrl: "/uploads/cakes/kue-klepon-gula-merah-lumer.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-4",
    name: "Kue Lapis Legit Spekoek",
    price: 65000,
    imageUrl: "/uploads/cakes/kue-lapis-legit-spekoek.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-5",
    name: "Kue Cucur Pandan Wangi",
    price: 2500,
    imageUrl: "/uploads/cakes/kue-cucur-pandan-wangi.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-6",
    name: "Biji Salak Ubi Manis",
    price: 15000,
    imageUrl: "/uploads/cakes/biji-salak-ubi-manis.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-7",
    name: "Bolu Gulung Pandan Keju",
    price: 35000,
    imageUrl: "/uploads/cakes/bolu-gulung-pandan-keju.jpg",
    isAvailable: true,
    category: "tart",
  },
  {
    id: "trad-8",
    name: "Kue Dadar Gulung Kelapa",
    price: 3000,
    imageUrl: "/uploads/cakes/kue-dadar-gulung-kelapa.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-9",
    name: "Kue Putu Ayu Kelapa Parut",
    price: 2500,
    imageUrl: "/uploads/cakes/kue-putu-ayu-kelapa-parut.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-10",
    name: "Kue Lapis Beras Pelangi",
    price: 3000,
    imageUrl: "/uploads/cakes/kue-lapis-beras-pelangi.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-11",
    name: "Kue Lemper Ayam Gurih",
    price: 4000,
    imageUrl: "/uploads/cakes/kue-lemper-ayam-gurih.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-12",
    name: "Kue Lumpur Kentang Kismis",
    price: 3500,
    imageUrl: "/uploads/cakes/kue-lumpur-kentang-kismis.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-13",
    name: "Kue Onde-Onde Wijen Kacang Hijau",
    price: 3000,
    imageUrl: "/uploads/cakes/kue-onde-onde-wijen-kacang-hijau.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-14",
    name: "Kue Bika Ambon Medan",
    price: 45000,
    imageUrl: "/uploads/cakes/kue-bika-ambon-medan.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-15",
    name: "Kue Pastel Goreng Renyah",
    price: 3500,
    imageUrl: "/uploads/cakes/kue-pastel-goreng-renyah.jpg",
    isAvailable: true,
    category: "pastry",
  },
  {
    id: "trad-16",
    name: "Kue Risoles Ragout Ayam",
    price: 4000,
    imageUrl: "/uploads/cakes/kue-risoles-ragout-ayam.jpg",
    isAvailable: true,
    category: "pastry",
  },
  {
    id: "trad-17",
    name: "Kue Nagasari Pisang",
    price: 2500,
    imageUrl: "/uploads/cakes/kue-nagasari-pisang.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-18",
    name: "Kue Semar Mendem",
    price: 4000,
    imageUrl: "/uploads/cakes/kue-semar-mendem.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-19",
    name: "Kue Wajik Ketan Gula Merah",
    price: 3000,
    imageUrl: "/uploads/cakes/kue-wajik-ketan-gula-merah.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
  {
    id: "trad-20",
    name: "Kue Carabikang Mekar",
    price: 3000,
    imageUrl: "/uploads/cakes/kue-carabikang-mekar.jpg",
    isAvailable: true,
    category: "kue-basah",
  },
];
